version: '3'
networks:
 app_network:
   name: fastnetwork
   driver: bridge
   
services:
  web:
    build:
      context: python
      dockerfile: ./DOCKERFILE
    volumes:
      - ./python:/app
    command: python app.py
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app_network
    depends_on:
      - mariadb
  newman:
    image: postman/newman:alpine
    command:
      run collections/iterator-test-nrg.json -k
      -e int.postman_environnement.json
      -r cli,json
      --reporter-json-export="collections/iterator-test.ng"
    volumes:
      - ./newman:/etc/newman
    depends_on:
      - web
      - mariadb
    networks:
      - app_network
  nginx:
    build:
      context: nginx
      dockerfile: DOCKERFILE
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - web
  mariadb:
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    volumes:
        - ./mysql/1-SCHEMA.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT}
      MYSQL_DATABASE: ${DATABASE_NAME}
    networks:
      - app_network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${PASSWORD_ROOT} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5