version: '3'
services:
  web:
    build:
      context: ./python
      dockerfile: ./DOCKERFILE-PYTHON
    command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
    depends_on:
      - mariadb
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${PASSWORD_ROOT}
      MARIADB_DATABASE: ${DATABASE_NAME}
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${PASSWORD_ROOT} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5