version: '3'

services:
    newman-dev:
        image: postman/newman:alpine
        command:
        run collections/iterator-test-nrg.json -k
        -e int.postman_environnement.json
        -r cli,json
        --reporter-json-export="collections/iterator-test.ng"
        volumes:
        - ../../../newman/collections:/etc/newman/collections
        - ./int.postman_environnement.json:/etc/newman/int.postman_environnement.json
        depends_on:
        - web
        - mariadb
        networks:
        - app_network