- name: "Generating docker compose file for nginx service"
  template:
    src: "compose.yml.j2"
    dest: "{{common.running_path}}/nginx/compose.yml"

- name: "Generating nginx config"
  template:
    src: "nginx.conf.j2"
    dest: "{{common.running_path}}/nginx/nginx.conf"