- name: Building environment
  hosts: localhost
  pre_tasks:
    - name: Create compose directory
      file:
        path: "{{common.running_path}}"
        state: directory
        owner: root
        group: root
        mode: '1777'
    - name: Create compose newman directory
      file:
        path: "{{common.running_path}}/newman"
        state: directory
        owner: root
        group: root
        mode: '1777'
    - name: Create compose python directory
      file:
        path: "{{common.running_path}}/python"
        state: directory
        owner: root
        group: root
        mode: '1777'
    - name: Create compose nginx directory
      file:
        path: "{{common.running_path}}/nginx"
        state: directory
        owner: root
        group: root
        mode: '1777'
  roles:
    - newman
    - nginx
    - python
    - app